export const FETCH_SESSION_REQUEST = 'FETCH_SESSION_REQUEST'
export const FETCH_SESSION_SUCCESS = 'FETCH_SESSION_SUCCESS'
export const FETCH_SESSION_FAILURE = 'FETCH_SESSION_FAILURE'

export const FETCH_MESSAGE_REQUEST = 'FETCH_MESSAGE_REQUEST'
export const FETCH_MESSAGE_SUCCESS = 'FETCH_MESSAGE_SUCCESS'
export const FETCH_MESSAGE_FAILURE = 'FETCH_MESSAGE_FAILURE'
